kind: pipeline
type: docker
name: build
steps:
  - name: build&push
    image: plugins/docker
    settings:
      repo: cruii/drone-feishu
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - push
  branch:
    - main
---
kind: pipeline
type: docker
name: go-build
steps:
  - name: go-build
    image: golang:1.21-alpine
    commands:
    - GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a -o drone-ci-feishu .
tigger:
  event:
    - pull_request
